### ISSUE TITLE
Running WiFi example on DISCO_F413ZH board

### ISSUE THREAD

**Issue by danny4478** [ARMmbed/wifi-ism43362#26]
I am trying to run the WiFi example https://github.com/ARMmbed/mbed-os-example-wifi on DISCO_F413ZH board, but the scan does not find any access points.
wifi->scan() returns 0 and I get “scan() failed with return value: 0”.
 
When ignoring the scan failure and attempt to connect I get this error:, 
NSAPI_ERROR_DEVICE_ERROR [failure interfacing with the network processor (-3012)]

Am I using a supported board? See pictures below.
Any other idea why this scan fails?

![img_1992](https://user-images.githubusercontent.com/15226523/43895663-bb331d94-9bde-11e8-8a36-64e8c5b079bf.JPG)
![img_1993](https://user-images.githubusercontent.com/15226523/43895664-bb552448-9bde-11e8-9f36-568f761859d2.JPG)

**Comment by jeromecoutant** [comment]
Hi

Yes, DISCO_F413ZH is a supported board,
and yes we have some issues with the scan procedure when wifi environment is very populated...

Is it working if you skip the full scan_demo part ?

**Comment by danny4478** [comment]
No.
When ignoring the scan failure and attempt to connect I get this error:
NSAPI_ERROR_DEVICE_ERROR [failure interfacing with the network processor (-3012)]

**Comment by LMESTM** [comment]
@danny4478  what jerome proposed as a test is to **skip the entire scan** part and directly go to the connect - have you tried that ?  There is a known issue in the firmware when too many APs around.

**Comment by danny4478** [comment]
Hi
After removing the entire scan part, and directly go to the connect as suggested, we get a successful connection.
@jeromecoutant @LMESTM Thanks for you support on this.

We are now trying to run this example on a Cypress PSoC 6 BT-WiFi board. Assuming we manage to add this new target to mbed-os, is there any reason this wifi example would not work on this board?

**Comment by jeromecoutant** [comment]
Hi
Maybe we can close this issue ?
Thx

**Comment by danny4478** [comment]
I have closed it.
Thanks
