### ISSUE TITLE
How to write and execute testcases for ble apps through icetea in mbed?

### ISSUE THREAD

**Issue by Vanireddy6** [ARMmbed/wifi-ism43362#35]

**Comment by jeromecoutant** [comment]
Hi
Note that wifi-ism43362 doesn't support BLE...

**Comment by 0xc0170** [comment]
@Vanireddy6 Can you provide more details, what have you tried? What would you like to test?

this seems to be better fit to ask in Mbed OS repository.

**Comment by jeromecoutant** [comment]
Please, open an issue in the mbed-os repo.
This repo is Wifi only...
Thx
