### ISSUE TITLE
Implementation of server socket

### ISSUE THREAD

**Issue by luiscavanillas** [ARMmbed/wifi-ism43362#52]
Hi,

I was wondering when "socket_bind", "socket_listen" and "socket_accept" will be supported so server sockets can be created.
I can't really manage to use the AT Commands correctly to start a server and manage client connections on my own.

Thanks in advance!

**Comment by jeromecoutant** [comment]
Hi @luiscavanillas 

I am sorry, but this request is not in ST plan...

@SeppoTakalo do you have any tips?

**Comment by luiscavanillas** [comment]
You can close the request, I finally implemented it on my own :)

**Comment by jeromecoutant** [comment]
Hi
Feel free to push a pull request :-)
