### ISSUE TITLE
Driver returns 0 for UDP socket recvfrom if called before sendto

### ISSUE THREAD

**Issue by kivaisan** [ARMmbed/wifi-ism43362#76]
If user has and UDP socket and first calls `recvfrom` before calling `sendto`, driver always returns data size of 0.
This is a bit confusing as 0 means packet with no data was received, which is not true. If driver hasn't received anything, it should return `NSAPI_ERROR_WOULD_BLOCK`.

**Comment by jeromecoutant** [comment]
@JeanMarcR

**Comment by JeanMarcR** [comment]
@kivaisan
Hi

Do you use the board B-L475E-IOT01A ?
 
Best regards

**Comment by kivaisan** [comment]
Yes. If I remember correcttly, the problem is in this part:
https://github.com/ARMmbed/wifi-ism43362/blob/master/ISM43362Interface.cpp#L479-L482

Internal connect flag is not set until user calls `sendto`.

**Comment by JeanMarcR** [comment]
@kivaisan
Hi
1 - ) socket.open()
2 - ) socket.connect()
3 - ) socket.recv() -> return 0

Please, could you tell me if it is the sequence of function calls you have done ?
Best regards

**Comment by kivaisan** [comment]
I don't remember anymore the use case where I found this, but I think your sequence is right.

**Comment by JeanMarcR** [comment]
@kivaisan

Please, could you check the following patch:
in file wifi-ism43362\ISM43362Interface.cpp
in function ISM43362Interface::socket_recv()

replace lines
   if (!socket->connected){
        _mutex.unlock();
	return 0;
    }

by lines

   if (!socket->connected){
        _mutex.unlock();
	if (socket->proto == NSAPI_UDP) {
	   return NSAPI_ERROR_WOULD_BLOCK; 
	}			
	return 0;
    }

**Comment by kivaisan** [comment]
@JeanMarcR Sorry, I'm currently working on another project, so I cannot test this right now.
