### ISSUE TITLE
Missing `set_blocking` and other blocking-related implementation

### ISSUE THREAD

**Issue by esajaa** [ARMmbed/wifi-ism43362#79]
At the moment there is no method of switching between blocking and non-blocking functionality, and the driver is always blocking.

**Comment by JeanMarcR** [comment]
At this time we were mainly or only relying on SYNC APIs.
I am not sure the driver can really evolve to support the ASYNC APIs, the module firmware AT-command communication method is mostly designed for synchronous communication.

**Comment by jeromecoutant** [comment]
Closing
